/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AkademikRouteImport } from './routes/akademik'
import { Route as AnalitikRouteImport } from './routes/analitik'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ImporDataRouteImport } from './routes/impor-data'
import { Route as ImporModulRouteImport } from './routes/impor-modul'
import { Route as InventarisRouteImport } from './routes/inventaris'
import { Route as KeamananRouteImport } from './routes/keamanan'
import { Route as KehadiranRouteImport } from './routes/kehadiran'
import { Route as KelasDigitalRouteImport } from './routes/kelas-digital'
import { Route as KesehatanRouteImport } from './routes/kesehatan'
import { Route as KeuanganRouteImport } from './routes/keuangan'
import { Route as KomunikasiRouteImport } from './routes/komunikasi'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as LokasiRouteImport } from './routes/lokasi'
import { Route as MasterDataRouteImport } from './routes/master-data'
import { Route as PerpustakaanRouteImport } from './routes/perpustakaan'
import { Route as SiswaSayaRouteImport } from './routes/siswa-saya'
import { Route as TugasTugasIdRouteImport } from './routes/tugas.$tugasId'
import { Route as UjianUjianIdRouteImport } from './routes/ujian.$ujianId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AkademikRoute = AkademikRouteImport.update({
  id: '/akademik',
  path: '/akademik',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalitikRoute = AnalitikRouteImport.update({
  id: '/analitik',
  path: '/analitik',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ImporDataRoute = ImporDataRouteImport.update({
  id: '/impor-data',
  path: '/impor-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ImporModulRoute = ImporModulRouteImport.update({
  id: '/impor-modul',
  path: '/impor-modul',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarisRoute = InventarisRouteImport.update({
  id: '/inventaris',
  path: '/inventaris',
  getParentRoute: () => rootRouteImport,
} as any)
const KeamananRoute = KeamananRouteImport.update({
  id: '/keamanan',
  path: '/keamanan',
  getParentRoute: () => rootRouteImport,
} as any)
const KehadiranRoute = KehadiranRouteImport.update({
  id: '/kehadiran',
  path: '/kehadiran',
  getParentRoute: () => rootRouteImport,
} as any)
const KelasDigitalRoute = KelasDigitalRouteImport.update({
  id: '/kelas-digital',
  path: '/kelas-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const KesehatanRoute = KesehatanRouteImport.update({
  id: '/kesehatan',
  path: '/kesehatan',
  getParentRoute: () => rootRouteImport,
} as any)
const KeuanganRoute = KeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => rootRouteImport,
} as any)
const KomunikasiRoute = KomunikasiRouteImport.update({
  id: '/komunikasi',
  path: '/komunikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const LokasiRoute = LokasiRouteImport.update({
  id: '/lokasi',
  path: '/lokasi',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataRoute = MasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const PerpustakaanRoute = PerpustakaanRouteImport.update({
  id: '/perpustakaan',
  path: '/perpustakaan',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaSayaRoute = SiswaSayaRouteImport.update({
  id: '/siswa-saya',
  path: '/siswa-saya',
  getParentRoute: () => rootRouteImport,
} as any)
const TugasTugasIdRoute = TugasTugasIdRouteImport.update({
  id: '/tugas/$tugasId',
  path: '/tugas/$tugasId',
  getParentRoute: () => rootRouteImport,
} as any)
const UjianUjianIdRoute = UjianUjianIdRouteImport.update({
  id: '/ujian/$ujianId',
  path: '/ujian/$ujianId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/akademik': typeof AkademikRoute
  '/analitik': typeof AnalitikRoute
  '/auth': typeof AuthRoute
  '/impor-data': typeof ImporDataRoute
  '/impor-modul': typeof ImporModulRoute
  '/inventaris': typeof InventarisRoute
  '/keamanan': typeof KeamananRoute
  '/kehadiran': typeof KehadiranRoute
  '/kelas-digital': typeof KelasDigitalRoute
  '/kesehatan': typeof KesehatanRoute
  '/keuangan': typeof KeuanganRoute
  '/komunikasi': typeof KomunikasiRoute
  '/laporan': typeof LaporanRoute
  '/lokasi': typeof LokasiRoute
  '/master-data': typeof MasterDataRoute
  '/perpustakaan': typeof PerpustakaanRoute
  '/siswa-saya': typeof SiswaSayaRoute
  '/tugas/$tugasId': typeof TugasTugasIdRoute
  '/ujian/$ujianId': typeof UjianUjianIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/akademik': typeof AkademikRoute
  '/analitik': typeof AnalitikRoute
  '/auth': typeof AuthRoute
  '/impor-data': typeof ImporDataRoute
  '/impor-modul': typeof ImporModulRoute
  '/inventaris': typeof InventarisRoute
  '/keamanan': typeof KeamananRoute
  '/kehadiran': typeof KehadiranRoute
  '/kelas-digital': typeof KelasDigitalRoute
  '/kesehatan': typeof KesehatanRoute
  '/keuangan': typeof KeuanganRoute
  '/komunikasi': typeof KomunikasiRoute
  '/laporan': typeof LaporanRoute
  '/lokasi': typeof LokasiRoute
  '/master-data': typeof MasterDataRoute
  '/perpustakaan': typeof PerpustakaanRoute
  '/siswa-saya': typeof SiswaSayaRoute
  '/tugas/$tugasId': typeof TugasTugasIdRoute
  '/ujian/$ujianId': typeof UjianUjianIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/akademik': typeof AkademikRoute
  '/analitik': typeof AnalitikRoute
  '/auth': typeof AuthRoute
  '/impor-data': typeof ImporDataRoute
  '/impor-modul': typeof ImporModulRoute
  '/inventaris': typeof InventarisRoute
  '/keamanan': typeof KeamananRoute
  '/kehadiran': typeof KehadiranRoute
  '/kelas-digital': typeof KelasDigitalRoute
  '/kesehatan': typeof KesehatanRoute
  '/keuangan': typeof KeuanganRoute
  '/komunikasi': typeof KomunikasiRoute
  '/laporan': typeof LaporanRoute
  '/lokasi': typeof LokasiRoute
  '/master-data': typeof MasterDataRoute
  '/perpustakaan': typeof PerpustakaanRoute
  '/siswa-saya': typeof SiswaSayaRoute
  '/tugas/$tugasId': typeof TugasTugasIdRoute
  '/ujian/$ujianId': typeof UjianUjianIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/akademik'
    | '/analitik'
    | '/auth'
    | '/impor-data'
    | '/impor-modul'
    | '/inventaris'
    | '/keamanan'
    | '/kehadiran'
    | '/kelas-digital'
    | '/kesehatan'
    | '/keuangan'
    | '/komunikasi'
    | '/laporan'
    | '/lokasi'
    | '/master-data'
    | '/perpustakaan'
    | '/siswa-saya'
    | '/tugas/$tugasId'
    | '/ujian/$ujianId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/akademik'
    | '/analitik'
    | '/auth'
    | '/impor-data'
    | '/impor-modul'
    | '/inventaris'
    | '/keamanan'
    | '/kehadiran'
    | '/kelas-digital'
    | '/kesehatan'
    | '/keuangan'
    | '/komunikasi'
    | '/laporan'
    | '/lokasi'
    | '/master-data'
    | '/perpustakaan'
    | '/siswa-saya'
    | '/tugas/$tugasId'
    | '/ujian/$ujianId'
  id:
    | '__root__'
    | '/'
    | '/akademik'
    | '/analitik'
    | '/auth'
    | '/impor-data'
    | '/impor-modul'
    | '/inventaris'
    | '/keamanan'
    | '/kehadiran'
    | '/kelas-digital'
    | '/kesehatan'
    | '/keuangan'
    | '/komunikasi'
    | '/laporan'
    | '/lokasi'
    | '/master-data'
    | '/perpustakaan'
    | '/siswa-saya'
    | '/tugas/$tugasId'
    | '/ujian/$ujianId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AkademikRoute: typeof AkademikRoute
  AnalitikRoute: typeof AnalitikRoute
  AuthRoute: typeof AuthRoute
  ImporDataRoute: typeof ImporDataRoute
  ImporModulRoute: typeof ImporModulRoute
  InventarisRoute: typeof InventarisRoute
  KeamananRoute: typeof KeamananRoute
  KehadiranRoute: typeof KehadiranRoute
  KelasDigitalRoute: typeof KelasDigitalRoute
  KesehatanRoute: typeof KesehatanRoute
  KeuanganRoute: typeof KeuanganRoute
  KomunikasiRoute: typeof KomunikasiRoute
  LaporanRoute: typeof LaporanRoute
  LokasiRoute: typeof LokasiRoute
  MasterDataRoute: typeof MasterDataRoute
  PerpustakaanRoute: typeof PerpustakaanRoute
  SiswaSayaRoute: typeof SiswaSayaRoute
  TugasTugasIdRoute: typeof TugasTugasIdRoute
  UjianUjianIdRoute: typeof UjianUjianIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akademik': {
      id: '/akademik'
      path: '/akademik'
      fullPath: '/akademik'
      preLoaderRoute: typeof AkademikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analitik': {
      id: '/analitik'
      path: '/analitik'
      fullPath: '/analitik'
      preLoaderRoute: typeof AnalitikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impor-data': {
      id: '/impor-data'
      path: '/impor-data'
      fullPath: '/impor-data'
      preLoaderRoute: typeof ImporDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impor-modul': {
      id: '/impor-modul'
      path: '/impor-modul'
      fullPath: '/impor-modul'
      preLoaderRoute: typeof ImporModulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventaris': {
      id: '/inventaris'
      path: '/inventaris'
      fullPath: '/inventaris'
      preLoaderRoute: typeof InventarisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keamanan': {
      id: '/keamanan'
      path: '/keamanan'
      fullPath: '/keamanan'
      preLoaderRoute: typeof KeamananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kehadiran': {
      id: '/kehadiran'
      path: '/kehadiran'
      fullPath: '/kehadiran'
      preLoaderRoute: typeof KehadiranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kelas-digital': {
      id: '/kelas-digital'
      path: '/kelas-digital'
      fullPath: '/kelas-digital'
      preLoaderRoute: typeof KelasDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kesehatan': {
      id: '/kesehatan'
      path: '/kesehatan'
      fullPath: '/kesehatan'
      preLoaderRoute: typeof KesehatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keuangan': {
      id: '/keuangan'
      path: '/keuangan'
      fullPath: '/keuangan'
      preLoaderRoute: typeof KeuanganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komunikasi': {
      id: '/komunikasi'
      path: '/komunikasi'
      fullPath: '/komunikasi'
      preLoaderRoute: typeof KomunikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lokasi': {
      id: '/lokasi'
      path: '/lokasi'
      fullPath: '/lokasi'
      preLoaderRoute: typeof LokasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data': {
      id: '/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof MasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perpustakaan': {
      id: '/perpustakaan'
      path: '/perpustakaan'
      fullPath: '/perpustakaan'
      preLoaderRoute: typeof PerpustakaanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa-saya': {
      id: '/siswa-saya'
      path: '/siswa-saya'
      fullPath: '/siswa-saya'
      preLoaderRoute: typeof SiswaSayaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tugas/$tugasId': {
      id: '/tugas/$tugasId'
      path: '/tugas/$tugasId'
      fullPath: '/tugas/$tugasId'
      preLoaderRoute: typeof TugasTugasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ujian/$ujianId': {
      id: '/ujian/$ujianId'
      path: '/ujian/$ujianId'
      fullPath: '/ujian/$ujianId'
      preLoaderRoute: typeof UjianUjianIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AkademikRoute: AkademikRoute,
  AnalitikRoute: AnalitikRoute,
  AuthRoute: AuthRoute,
  ImporDataRoute: ImporDataRoute,
  ImporModulRoute: ImporModulRoute,
  InventarisRoute: InventarisRoute,
  KeamananRoute: KeamananRoute,
  KehadiranRoute: KehadiranRoute,
  KelasDigitalRoute: KelasDigitalRoute,
  KesehatanRoute: KesehatanRoute,
  KeuanganRoute: KeuanganRoute,
  KomunikasiRoute: KomunikasiRoute,
  LaporanRoute: LaporanRoute,
  LokasiRoute: LokasiRoute,
  MasterDataRoute: MasterDataRoute,
  PerpustakaanRoute: PerpustakaanRoute,
  SiswaSayaRoute: SiswaSayaRoute,
  TugasTugasIdRoute: TugasTugasIdRoute,
  UjianUjianIdRoute: UjianUjianIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
